obj-y += clone.o
obj-y += cpu.o
obj-y += exec.o
obj-y += futex.o
obj-y += irq.o
obj-y += pagefault.o
obj-y += proc.o
obj-y += scavenger.o
obj-y += sched.o
obj-y += sys.o
obj-y += syscall.o
obj-y += sysfile.o
obj-y += sysproc.o
obj-y += thread_group.o
obj-y += trap.o

obj-y += asm/