obj-y += uart.o
obj-y += virtio_disk.o

# obj-y += dmac.o
# obj-y += gpio.o
obj-y += sdcard.o
obj-y += spi.o
obj-y += sysctl.o
obj-y += fpioa.o
obj-y += gpiohs.o
obj-y += ff.o
obj-y += diskio.o
obj-y += ccsbcs.o