obj-y += alloc.o
obj-y += copy.o
obj-y += filemap.o
obj-y += io.o
# obj-y += memory.o
obj-y += mmap.o
obj-y += page.o
obj-y += page-writeback.o
obj-y += pdflush.o
obj-y += slob.o
# obj-y += swap.o
obj-y += trapframe.o
obj-y += vm.o
obj-y += vma.o
# obj-y += vmscan.o

# buddy or freelist
obj-y += buddy.o
# obj-y += freelist.o
