obj-y += alloc.o
obj-y += copy.o
obj-y += filemap.o
obj-y += io.o
obj-y += mmap.o
obj-y += page.o
obj-y += page-writeback.o
obj-y += pdflush.o
obj-y += slob.o
obj-y += trapframe.o
obj-y += vm.o
obj-y += vma.o

# buddy or freelist
obj-y += buddy.o
# obj-y += freelist.o
