#define sys_fork    1
#define sys_exit    2
#define sys_wait    3
#define sys_pipe    4
#define sys_read    5
#define sys_kill    6
#define sys_exec    7
#define sys_fstat   8
#define sys_chdir   9
#define sys_dup     10
#define sys_getpid  11
#define sys_sbrk    12
#define sys_sleep   13
#define sys_uptime  14
#define sys_open    15
#define sys_write   16
#define sys_mknod   17
#define sys_unlink  18
#define sys_link    19
#define sys_mkdir   20
#define sys_close   21
#define sys_test    99